# Название приложения
spring.application.name=demo
server.port=8080

# === H2 Console (для просмотра БД) ===
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# === Подключение к in-memory H2 ===
spring.datasource.url=jdbc:h2:mem:bankdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# === Отключаем автоматическое управление схемой через Hibernate ===
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
# Показывать SQL
spring.jpa.show-sql=true

# === Включаем инициализацию БД из SQL-файлов ===
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql



# Логировать параметры запросов
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
